version: "3.0"

services:
  postgres:
    container_name: postgres
    image: postgres:14
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD=61665786
      - POSTGRES_USER=postgres
      - POSTGRES_DB=trello-api
    ports: 
      - ${POSTGRES_PORT:-5432}:5432
    tty: true
    volumes: 
      - pgdata:/var/lib/postgresql/data
    restart: always
  main:
    container_name: main
    build:
      context: .
    env_file:
      - .env
    volumes:
      - .:/app
      - ./app/node_modules
    ports: 
      - 8000:8000
      - 9229:9229
    environment:
      - DB_HOST=postgres
    command: npm run start
    depends_on: 
      - postgres
    restart: always
    links:
      - postgres
  migration:
    build:
      context: .
    command:
      [
        "./wait-for-it/wait-for-it.sh",
        "postgres:5432",
        "--",
        "npm",
        "run",
        "migrate"
      ]
    links:
      - postgres
    depends_on:
      - postgres
    env_file: 
      - .env
    environment:
      - DB_HOST=postgres

volumes: 
  pgdata: null
